local options = {
    ensure_installed = {
        "asm",
        "bash",
        "bibtex",
        "c",
        "cmake",
        "cpp",
        "css",
        "csv",
        "cuda",
        "dockerfile",
        "fish",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "html",
        "javascript",
        "latex",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nasm",
        "ninja",
        "python",
        "rust",
        "r",
        "sql",
        "toml",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zig",
    },

    auto_install = true,

    highlight = {
        enable = true,
        use_languagetree = true,
    },

    indent = { enable = true },
}

return options
